apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: temporal-autoscaling-demo
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app.kubernetes.io/name: temporal-autoscaling-demo
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: worker
        image: ghcr.io/alexandreroman/temporal-autoscaling-demo-worker:latest
        ports:
        - containerPort: 9081
          name: management
        envFrom:
        - secretRef:
            name: temporal-connection
        - secretRef:
            name: otel
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: management
          initialDelaySeconds: 15
          periodSeconds: 10
