apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker
  namespace: temporal-autoscaling-demo
spec:
  scaleTargetRef:
    name: worker
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: temporal-task-queue
      metadata:
        serverAddress: "temporal-frontend.temporal:7233"
        namespace: "default"
        taskQueue: "order-processing"
        targetBacklogSize: "5"
        activationTargetBacklogSize: "1"
