apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker
  namespace: temporal-autoscaling-demo
spec:
  scaleTargetRef:
    name: worker
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: temporal
      metadata:
        endpoint: "temporal-frontend.temporal:7233"
        namespace: "default"
        taskQueue: "order-processing"
        targetQueueSize: "5"
        activationTargetQueueSize: "1"
