# ClusterIP Service exposing the console
# deployment within the cluster.
apiVersion: v1
kind: Service
metadata:
  name: autoscaling-demo-console
  namespace: temporal-autoscaling-demo
spec:
  selector:
    app: autoscaling-demo-console
  ports:
    - port: 80
      targetPort: http
      name: http
