apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal-autoscaling-demo
resources:
  - namespace.yaml
  - worker
  - console
secretGenerator:
  - name: temporal-connection
    literals:
      - TEMPORAL_ADDRESS=temporal-frontend.temporal:7233
      - TEMPORAL_NAMESPACE=default
  - name: otel
    literals:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector.opentelemetry:4318
