spring:
  application:
    name: autoscaling-demo-console

  temporal:
    connection:
      target: ${TEMPORAL_ADDRESS:localhost:7233}
    namespace: ${TEMPORAL_NAMESPACE:default}

  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  structured:
    format:
      console: ecs

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: ${PORT:8080}
